### ISSUE TITLE
Adding default resources file

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/cookiecutter-osparc-service#103]
I think it might be a good idea to add a resources configuration file, e.g. like [`runtime.yml`](https://github.com/ITISFoundation/tvb-recon/blob/main/.osparc/runtime.yml).

By default, we can add the values that are assigned to computational services if none is provided. Where can I find them @sanderegg?

Also during the webinar on the cookiecutter one attendee asked about what are the limits, so if we add that file this will be more explicit. I can also add an explanation in the `README.md` on how this file should be used/modified (and this would be an optional step in the workflow for creating a service).

@pcrespov, @sanderegg, do you foresee problems with adding the `runtime.yml` to this cookiecutter?

**Comment by pcrespov** [comment]
@elisabettai yes, OOIL will be able to recognize ``runtime.yml``

https://github.com/ITISFoundation/osparc-simcore/blob/17d49db7ca29e0ca04fca31a3ab3419505671276/packages/service-integration/src/service_integration/commands/compose.py#L176

so go ahead and integrate it in the cookiecutter. I will be happy to review your PR afterwards.

Regarding the doc, go ahead but I would not expose too much functionality until the interface (i.e. the properties we can change etc) is well defined and closed.
