### ISSUE TITLE
Fixes configuration of monitoring stack

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/cookiecutter-osparc-service#20]
Prometheus does not connect to some services because the service hostnames have changed. 

Access to prometheus targets in master environment deploy show:
![image.png](https://images.zenhubusercontent.com/5caef818ecad11531cc41364/68b7cbd8-bea4-482e-a8dd-fb439b7921c1)

Possible cause:
- Changes in the services host names seem to be the cause of the problem: e.g. before ``webserver`` and now ``master_webserver``  etc

@sanderegg  what do you think?

**Comment by sanderegg** [comment]
updated monitoring stack.
masu dockerd-exporter is not connected since the docker_gwbridge is incorrect over there. probable solution is to follow [this](https://success.docker.com/article/how-do-i-change-the-docker-gwbridge-address)

**Comment by pcrespov** [comment]
> master_webserver:8080/metrics does not return anything??

tmp disabled. @sanderegg  perhaps you can then close this issue?

**Comment by sanderegg** [comment]
issue completed.
